#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -I src/H -I /usr/local/include/armadillo_bits -I /usr/include 
CFLAGS = -Wall -fexceptions -std=c++11
RESINC = 
LIBDIR = 
LIB = -ldl /usr/local/lib/libarmadillo.so.6.500.5 /usr/lib/libfftw.so  -lboost_iostreams -lboost_system -lboost_filesystem 
LDFLAGS = 

INC_DEBUG = $(INC) -I src/H
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB) 
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/ksdft++
INC_RELEASE = $(INC) -I src/H
CFLAGS_RELEASE = $(CFLAGS) -O3
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/ksdft++

OBJ_DEBUG =  $(OBJDIR_DEBUG)/src/C/Linv.o $(OBJDIR_DEBUG)/src/C/O.o $(OBJDIR_DEBUG)/src/C/atomicSystem.o $(OBJDIR_DEBUG)/src/C/cI.o $(OBJDIR_DEBUG)/src/C/cIdag.o $(OBJDIR_DEBUG)/src/C/cJ.o $(OBJDIR_DEBUG)/src/C/cJdag.o $(OBJDIR_DEBUG)/src/C/gnuPlotPlotting.o $(OBJDIR_DEBUG)/src/C/inputParser.o $(OBJDIR_DEBUG)/src/C/ionicPotentialClass.o $(OBJDIR_DEBUG)/src/C/latexComment.o $(OBJDIR_DEBUG)/src/C/main.o $(OBJDIR_DEBUG)/src/C/L.o $(OBJDIR_DEBUG)/src/C/pccgOptimizer.o $(OBJDIR_DEBUG)/src/C/sdOptimizer.o $(OBJDIR_DEBUG)/src/C/testingClass.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/C/Linv.o $(OBJDIR_RELEASE)/src/C/O.o $(OBJDIR_RELEASE)/src/C/atomicSystem.o $(OBJDIR_RELEASE)/src/C/cI.o $(OBJDIR_RELEASE)/src/C/cIdag.o $(OBJDIR_RELEASE)/src/C/cJ.o $(OBJDIR_RELEASE)/src/C/cJdag.o $(OBJDIR_RELEASE)/src/C/gnuPlotPlotting.o $(OBJDIR_RELEASE)/src/C/inputParser.o $(OBJDIR_RELEASE)/src/C/ionicPotentialClass.o $(OBJDIR_RELEASE)/src/C/latexComment.o $(OBJDIR_RELEASE)/src/C/main.o $(OBJDIR_RELEASE)/src/C/L.o $(OBJDIR_RELEASE)/src/C/pccgOptimizer.o $(OBJDIR_RELEASE)/src/C/sdOptimizer.o $(OBJDIR_RELEASE)/src/C/testingClass.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src/C || mkdir -p $(OBJDIR_DEBUG)/src/C

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)


$(OBJDIR_DEBUG)/src/C/Linv.o: src/C/Linv.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/Linv.cpp -o $(OBJDIR_DEBUG)/src/C/Linv.o

$(OBJDIR_DEBUG)/src/C/O.o: src/C/O.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/O.cpp -o $(OBJDIR_DEBUG)/src/C/O.o

$(OBJDIR_DEBUG)/src/C/atomicSystem.o: src/C/atomicSystem.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/atomicSystem.cpp -o $(OBJDIR_DEBUG)/src/C/atomicSystem.o

$(OBJDIR_DEBUG)/src/C/cI.o: src/C/cI.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/cI.cpp -o $(OBJDIR_DEBUG)/src/C/cI.o

$(OBJDIR_DEBUG)/src/C/cIdag.o: src/C/cIdag.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/cIdag.cpp -o $(OBJDIR_DEBUG)/src/C/cIdag.o

$(OBJDIR_DEBUG)/src/C/cJ.o: src/C/cJ.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/cJ.cpp -o $(OBJDIR_DEBUG)/src/C/cJ.o

$(OBJDIR_DEBUG)/src/C/cJdag.o: src/C/cJdag.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/cJdag.cpp -o $(OBJDIR_DEBUG)/src/C/cJdag.o

$(OBJDIR_DEBUG)/src/C/gnuPlotPlotting.o: src/C/gnuPlotPlotting.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/gnuPlotPlotting.cpp -o $(OBJDIR_DEBUG)/src/C/gnuPlotPlotting.o

$(OBJDIR_DEBUG)/src/C/inputParser.o: src/C/inputParser.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/inputParser.cpp -o $(OBJDIR_DEBUG)/src/C/inputParser.o

$(OBJDIR_DEBUG)/src/C/ionicPotentialClass.o: src/C/ionicPotentialClass.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/ionicPotentialClass.cpp -o $(OBJDIR_DEBUG)/src/C/ionicPotentialClass.o

$(OBJDIR_DEBUG)/src/C/latexComment.o: src/C/latexComment.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/latexComment.cpp -o $(OBJDIR_DEBUG)/src/C/latexComment.o

$(OBJDIR_DEBUG)/src/C/main.o: src/C/main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/main.cpp -o $(OBJDIR_DEBUG)/src/C/main.o

$(OBJDIR_DEBUG)/src/C/L.o: src/C/L.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/L.cpp -o $(OBJDIR_DEBUG)/src/C/L.o

$(OBJDIR_DEBUG)/src/C/pccgOptimizer.o: src/C/pccgOptimizer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/pccgOptimizer.cpp -o $(OBJDIR_DEBUG)/src/C/pccgOptimizer.o

$(OBJDIR_DEBUG)/src/C/sdOptimizer.o: src/C/sdOptimizer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/sdOptimizer.cpp -o $(OBJDIR_DEBUG)/src/C/sdOptimizer.o

$(OBJDIR_DEBUG)/src/C/testingClass.o: src/C/testingClass.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/C/testingClass.cpp -o $(OBJDIR_DEBUG)/src/C/testingClass.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src/C

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src/C || mkdir -p $(OBJDIR_RELEASE)/src/C

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/C/Linv.o: src/C/Linv.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/Linv.cpp -o $(OBJDIR_RELEASE)/src/C/Linv.o

$(OBJDIR_RELEASE)/src/C/O.o: src/C/O.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/O.cpp -o $(OBJDIR_RELEASE)/src/C/O.o

$(OBJDIR_RELEASE)/src/C/atomicSystem.o: src/C/atomicSystem.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/atomicSystem.cpp -o $(OBJDIR_RELEASE)/src/C/atomicSystem.o

$(OBJDIR_RELEASE)/src/C/cI.o: src/C/cI.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/cI.cpp -o $(OBJDIR_RELEASE)/src/C/cI.o

$(OBJDIR_RELEASE)/src/C/cIdag.o: src/C/cIdag.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/cIdag.cpp -o $(OBJDIR_RELEASE)/src/C/cIdag.o

$(OBJDIR_RELEASE)/src/C/cJ.o: src/C/cJ.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/cJ.cpp -o $(OBJDIR_RELEASE)/src/C/cJ.o

$(OBJDIR_RELEASE)/src/C/cJdag.o: src/C/cJdag.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/cJdag.cpp -o $(OBJDIR_RELEASE)/src/C/cJdag.o

$(OBJDIR_RELEASE)/src/C/gnuPlotPlotting.o: src/C/gnuPlotPlotting.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/gnuPlotPlotting.cpp -o $(OBJDIR_RELEASE)/src/C/gnuPlotPlotting.o

$(OBJDIR_RELEASE)/src/C/inputParser.o: src/C/inputParser.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/inputParser.cpp -o $(OBJDIR_RELEASE)/src/C/inputParser.o

$(OBJDIR_RELEASE)/src/C/ionicPotentialClass.o: src/C/ionicPotentialClass.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/ionicPotentialClass.cpp -o $(OBJDIR_RELEASE)/src/C/ionicPotentialClass.o

$(OBJDIR_RELEASE)/src/C/latexComment.o: src/C/latexComment.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/latexComment.cpp -o $(OBJDIR_RELEASE)/src/C/latexComment.o

$(OBJDIR_RELEASE)/src/C/main.o: src/C/main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/main.cpp -o $(OBJDIR_RELEASE)/src/C/main.o

$(OBJDIR_RELEASE)/src/C/L.o: src/C/L.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/L.cpp -o $(OBJDIR_RELEASE)/src/C/L.o

$(OBJDIR_RELEASE)/src/C/pccgOptimizer.o: src/C/pccgOptimizer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/pccgOptimizer.cpp -o $(OBJDIR_RELEASE)/src/C/pccgOptimizer.o

$(OBJDIR_RELEASE)/src/C/sdOptimizer.o: src/C/sdOptimizer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/sdOptimizer.cpp -o $(OBJDIR_RELEASE)/src/C/sdOptimizer.o

$(OBJDIR_RELEASE)/src/C/testingClass.o: src/C/testingClass.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/C/testingClass.cpp -o $(OBJDIR_RELEASE)/src/C/testingClass.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src/C

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

